CREATE TABLE IF NOT EXISTS tb_developer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(120) NOT NULL,
    email VARCHAR(120) NOT NULL UNIQUE,
    nickname VARCHAR(30) NOT NULL UNIQUE,
    uf VARCHAR(2) NOT NULL
);

CREATE TABLE IF NOT EXISTS tb_developer_experience (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    years_of_experience INT NOT NULL,
    primary_language VARCHAR(50) NOT NULL,
    interested_in_ai BOOLEAN NOT NULL,
    skills VARCHAR(300) NOT NULL,
    CONSTRAINT fk_experience_user FOREIGN KEY (user_id) REFERENCES tb_developer(id) ON DELETE CASCADE
);
